FROM mdillon/postgis

ENV POSTGRES_PASSWORD pass
ENV POSTGRES_DB junction

EXPOSE 9876

ADD possu.sql /docker-entrypoint-initdb.d/

RUN echo "host all  all    0.0.0.0/0  md5" >> /var/lib/postgresql/data/pg_hba.conf
