# Generated by Django 2.2.7 on 2019-11-15 19:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_id_asta', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'junction_counter',
            },
        ),
        migrations.CreateModel(
            name='NationalPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_park_code', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'junction_national_park',
            },
        ),
        migrations.CreateModel(
            name='ParkVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('visits', models.IntegerField(default=0)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junctionbackend.Counter')),
            ],
            options={
                'db_table': 'junction_park_visitors',
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='national_park_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junctionbackend.NationalPark'),
        ),
    ]
