# Generated by Django 2.2.7 on 2019-11-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='national_park_code',
            new_name='national_park',
        ),
    ]
