# Generated by Django 2.2.7 on 2019-11-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0004_tag_trailtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=900, unique=True)),
            ],
            options={
                'db_table': 'junction_question',
            },
        ),
        migrations.CreateModel(
            name='TrailQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junctionbackend.Question')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='junctionbackend.Trail')),
            ],
            options={
                'db_table': 'junction_trail_question',
            },
        ),
    ]
