# Generated by Django 2.2.7 on 2019-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0005_question_trailquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
