# Generated by Django 2.2.7 on 2019-11-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0007_auto_20191116_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='range_end',
            new_name='range_length',
        ),
        migrations.RemoveField(
            model_name='question',
            name='range_start',
        ),
    ]
