# Generated by Django 2.2.7 on 2019-11-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0008_auto_20191116_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='range_length',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
