# Generated by Django 2.2.7 on 2019-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0011_question_slider_value_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='lenght',
            field=models.IntegerField(default=0),
        ),
    ]
