# Generated by Django 2.2.7 on 2019-11-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0012_trail_lenght'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='lenght',
            new_name='length',
        ),
    ]
