# Generated by Django 2.2.7 on 2019-11-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0013_auto_20191116_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon_url',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
