# Generated by Django 2.2.7 on 2019-11-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junctionbackend', '0014_auto_20191116_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ordinal',
            field=models.IntegerField(default=0),
        ),
    ]
